oss_list:
  - name: 'Redmine'
    version: '5.0.2'
    release_date: '2022/10/21'
    input_file: 'data/0_raw/redmine_v5.0.2_blackduck.xlsx'
  - name: 'Node.js'
    version: '18.7.0'
    release_date: '2022/10/21'
    input_file: 'data/0_raw/node_js_dev_v18.7.0_blackduck.xlsx'
  - name: 'Camunda'
    version: '7.17'
    release_date: '2022/10/21'
    input_file: 'data/0_raw/camunda_v7.17_blackduck.xlsx'
  - name: 'ExastroIT Automation'
    version: '1.10.0'
    release_date: '2022/10/21'
    input_file: 'data/0_raw/exastro_ita_v1.10.0_blackduck.xlsx'
  - name: 'Keycloak'
    version: '15.1.1'
    release_date: '2022/10/21'
    input_file: 'data/0_raw/keycloak-v15.1.1-blackduck.xlsx'
  - name: 'Tomcat'
    version: '10.0.23'
    release_date: '2022/10/21'
    input_file: 'data/0_raw/tomcat_v10.0.23_blackduck.xlsx'
  
summary_report:
  template: 'summary_report.html'
  xlsx: 'data/3_reports/summary_report.xlsx'
  html: 'data/3_reports/summary_report.html'