oss_list:
  - name: 'Redmine'
    version: '5.0.2'
    release_date: '2022/10/21'
    input_file: 'data/0_raw/redmine_5.0.2_blackduck.xlsx'
  - name: 'Node.js'
    version: '18.7.0'
    release_date: '2022/10/21'
    input_file: 'data/0_raw/nodejs_18.7.0_blackduck.xlsx'
  - name: 'Camunda'
    version: '7.17'
    release_date: '2022/10/21'
    input_file: 'data/0_raw/camunda_7.17.0_blackduck.xlsx'
  - name: 'ExastroIT Automation'
    version: '1.10.0'
    release_date: '2022/10/21'
    input_file: 'data/0_raw/exastro_ita_1.10.0_blackduck.xlsx'
  - name: 'Keycloak'
    version: '15.1.1'
    release_date: '2022/10/21'
    input_file: 'data/0_raw/keycloak_15.1.1_blackduck.xlsx'
  - name: 'Tomcat'
    version: '10.0.23'
    release_date: '2022/10/21'
    input_file: 'data/0_raw/tomcat_10.0.23_blackduck.xlsx'

summary_report:
  template: 'summary_report.html'
  xlsx: 'data/3_reports/summary_report.xlsx'
  html: 'data/3_reports/summary_report.html'